my_list = []

my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)
my_list.append(-113)

print("Slot 0 contains a", my_list[0])
print("Slot 1 contains a", my_list[1])
print("Slot 2 contains a", my_list[2])
print("Slot 3 contains a", my_list[3])
print("Slot 4 contains a", my_list[4])
print("Slot 5 contains a", my_list[5])
print("Slot 6 contains a", my_list[6])
print("Slot 7 contains a", my_list[7])
print("Slot 8 contains a", my_list[8])
print("Slot 9 contains a", my_list[9])